/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.ConexionBD;
import DAO.IConexionBD;
import DAO.ILicenciaDAO;
import DAO.IPersonaDAO;
import DAO.IPlacaDAO;
import DAO.IVehiculoDAO;
import DAO.LicenciaDAO;
import DAO.PersonaDAO;
import DAO.PlacaDAO;
import DAO.VehiculoDAO;
import Entidades.Licencia;
import Entidades.Persona;
import Entidades.Vehiculo;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author oscar
 */
public class frmMenuPrincipal extends javax.swing.JFrame {
    
   /**
    * Objeto de tipo persona
    */
   Persona persona; 
   
    public frmMenuPrincipal() {
        initComponents();
    }
    
    /**
     * Método constructor utilizado para devolver la rfc de la persona registrada
     * @param persona Persona a la cual se registro
     */
    public frmMenuPrincipal(Persona persona) {
        initComponents();
        txtRFC.setText(persona.getRfc());
    }
    
    /**
     * Método utilizado para encontrar si una persona encuentra almacenada en la bd 
     * mediante el rfc
     * @return falso si no lo encuentra, true de lo contrario
     */
    public boolean encontrarPersona(){
        IConexionBD conexion=new ConexionBD();
        IPersonaDAO personaDAO= new PersonaDAO(conexion);
        persona=personaDAO.buscarPersona(txtRFC.getText());
        if(persona==null){
             JOptionPane.showMessageDialog(this, "No se pudo encontro la persona");
             return false;
        }
        else{
            return true;
        }
        
    }
    
    public boolean verificarLista(){
        IConexionBD conexion=new ConexionBD();
        ILicenciaDAO lic = new LicenciaDAO(conexion);
        List<Licencia> licencia = lic.listarLicenciaVigentesPersona(persona.getRfc());
        
        if(licencia.isEmpty()){
            JOptionPane.showMessageDialog(this, "La persona no cuenta con una licencia vigente");
            return false;
        
        }
        return true;
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVehiculo = new javax.swing.JButton();
        btnPlacas = new javax.swing.JButton();
        btnLicencia = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnPersona = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnHistorial = new javax.swing.JButton();
        txtRFC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Menu principal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        btnVehiculo.setText("Registrar vehiculo");
        btnVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculoActionPerformed(evt);
            }
        });
        getContentPane().add(btnVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        btnPlacas.setText("Solicitar placas");
        btnPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlacasActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 124, -1));

        btnLicencia.setText("Solicitar licencia");
        btnLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicenciaActionPerformed(evt);
            }
        });
        getContentPane().add(btnLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 124, -1));

        btnSalir.setText("Salir");
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        btnReporte.setText("Mostrar reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        getContentPane().add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 124, -1));

        btnPersona.setText("Registrar cliente");
        btnPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 140, -1));

        jLabel2.setText("Persona interesada (RFC)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        btnHistorial.setText("Mostrar historial");
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 130, -1));

        txtRFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRFCKeyTyped(evt);
            }
        });
        getContentPane().add(txtRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 110, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonaActionPerformed
        // TODO add your handling code here:
        IConexionBD conexion=new ConexionBD();
        IPersonaDAO personaDAO= new PersonaDAO(conexion);
        frmPersona persona= new frmPersona(personaDAO);
        persona.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPersonaActionPerformed
    /**
     * Método que al dar click en el boton si se encuentra a la persona nos
     * manda al frame de registro de vehículo
     * @param evt evt
     */
    private void btnVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculoActionPerformed
        
        
        if (encontrarPersona()) {
            IConexionBD conexion = new ConexionBD();
            IVehiculoDAO vehiculoDAO = new VehiculoDAO(conexion);
            frmVehiculo vehiculo = new frmVehiculo(vehiculoDAO, persona);
            vehiculo.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_btnVehiculoActionPerformed
    
    /**
     * Método que si se encuntra a la persona la manda a la pantalla de Placas
     * @param evt evt
     */
    private void btnPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlacasActionPerformed
        if (encontrarPersona()) {
            if(!verificarLista()){
                return;
            }
        IConexionBD conexion = new ConexionBD();
        IPlacaDAO placaDAO = new PlacaDAO(conexion);
        IVehiculoDAO vehiculoDAO = new VehiculoDAO(conexion);
        frmPlacas placas= new frmPlacas(placaDAO, vehiculoDAO, persona);
        placas.setVisible(true);
        this.dispose();
        }
        
    }//GEN-LAST:event_btnPlacasActionPerformed

    private void btnLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicenciaActionPerformed
        if (encontrarPersona()) {
        IConexionBD conexion = new ConexionBD();
        ILicenciaDAO lcd = new LicenciaDAO(conexion);
        frmLicencia licencia= new frmLicencia(persona,lcd);
        licencia.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_btnLicenciaActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
        frmReporte reporte= new frmReporte();
        reporte.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
        IConexionBD conexion=new ConexionBD();
        IPersonaDAO personaDAO= new PersonaDAO(conexion);
        frmHistorial historial= new frmHistorial(personaDAO);
        historial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistorialActionPerformed
    /**
     * Método que valida el campo de rfc
     * @param evt evt
     */
    private void txtRFCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFCKeyTyped
        char c = evt.getKeyChar();
        
        if((c<'0' || c>'9') && (c<'A' )| c>'Z')evt.consume();
        
        if(txtRFC.getText().length()==13){
            evt.consume();
        }
        
        
    }//GEN-LAST:event_txtRFCKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnLicencia;
    private javax.swing.JButton btnPersona;
    private javax.swing.JButton btnPlacas;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtRFC;
    // End of variables declaration//GEN-END:variables
}
